name: vanilla-react

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VanillaReact.Api

    steps:
      - uses: actions/checkout@v2
      - name: Setup Api
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
